library(ggplot2)
df <- data.frame(Samples = paste0('sample',1:12), 
           Sample_Name = c('H-5-B',
                           'H-8-B',
                           'H-14-B',
                           'H-5-S',
                           'H-8-S',
                           'H-14-S',
                           'B-10-B',
                           'B-13-B',
                           'B-17-B',
                           'B-10-S',
                           'B-13-S',
                           'B-17-S'),
           Plate = c('C1',
                     '',
                     '',
                     '',
                     '',
                     '',
                     '',
                     '',
                     '',
                     '',
                     '',
                     'F2'),
           Group = c('B', 'B', 'B', 'S', 'S', 'S',
                     'B', 'B', 'B', 'S', 'S', 'S'),
         BCV1 = c(-0.8,
              -0.6,
              -0.5,
              0.75,
              0.85,
              0.8,
              -0.5,
              -0.6,
              -0.8,
              0.8,
              0.4,
              0.1), 
         BCV2 = c(-1.9,
               0.4,
               0.25,
               0.1,
               0.25,
               -0.2,
               0.45,
               0.3,
               0.5,
               0.2,
               -0.2,
              -0.5))

ggplot(data = df, aes(x = BCV1, y = BCV2, col = Group, label = Plate)) + geom_point()+ geom_text(aes(label = Plate), vjust = -1, hjust = 0.5)
